### ISSUE TITLE
blast from the past!

### ISSUE THREAD

**Issue by jpollack** [dest4/stream-audio-fingerprint#1]
Hi!  You don't know me, I don't;t I know you, but I couldn't believe my eyes when randomly skimming reddit I saw your post.  For reasons soon to be apparent it and it filled me with joy and happy memories)

Well more than a decade ago (I think 2001), me and some wet behind the ears friends had this crazy idea that had never occurred to anyone before -- through the constructor of certain transfer functions, we could _APPROXIMATE_ a metric space of sound, where distance corresponded to "how similar are these two sounds"  This metric, when combined with more classical ML tools like PCA then SVM then Q trees for search  and neighborest matching (thoughthat was slow) allowed us to so what felt at the time completely unheard of.  We could actually take a random CD from an investors car, play any point on it, and within seconds know exactly the song and location.

But what _I_ was always more curious about is the function AXA not AXB.  THe function showing varying levels of self similarity within the same clip i just KNEW would eventually be worth it and at the least, it's really cool!

So, in the final death throws of the company, I put together  a quick demo that would take as input audio stations and give as output exact timestmps of every time every single commercial was played.  I thouhght it was cool, but had no idea of anyone would want such a thing.  

Anyway, I'm nto sure where I was going but thanks for a pleasant walk down memory land, =)

**Comment by dest4** [comment]
Glad you could recall good memories! In the field of "how similar are these two sounds", I'm thinking about the EchoNest/Spotify API that gives danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo
https://developer.spotify.com/web-api/get-several-audio-features/
But of course it did not exist in 2001.
PS: I'm closing the issue, but feel free to continue the discussion!
