### ISSUE TITLE
plotting landmarks

### ISSUE THREAD

**Issue by loretoparisi** [dest4/stream-audio-fingerprint#10]
Hello, I have tried to do some plotting turning `DO_PLOT=true`.
It works, but the plots seems to be stretched in some way
![out-fft](https://user-images.githubusercontent.com/163333/50353803-a6298080-0549-11e9-8aa6-b82487b9900e.png)
![out-thr](https://user-images.githubusercontent.com/163333/50353805-a6298080-0549-11e9-8ebb-66e48d63fdfb.png)
Any idea?

Thanks again for your help!

**Comment by dest4** [comment]
Check the sampling rate of your file vs that given to ffmpeg?

**Comment by loretoparisi** [comment]
```
ffprobe version 4.0 Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mp3, from '/root/audio/1000449.mp3':
  Metadata:
    encoder         : Lavf58.12.100
  Duration: 00:06:18.12, start: 0.023021, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc58.18
```

it's the input audio while my settings was

```javascript
const args = [
        '-y',
        '-loglevel', loglevel,
        //'-i', 'pipe:0',
        '-i', uri,
        '-acodec', 'pcm_s16le',
        '-ar', 22050,
        '-ac', 1,
        '-f', 'wav',
        '-v', 'fatal',
        'pipe:1'
      ];
```

I have tried to set `'-ar', 48000,` but it seems that it does not work properly.

**Comment by dest4** [comment]
Stupid suggestion: does the file you are analysing have a broad spectrum, or is it only bass sound (e.g. at the beginning) ?

**Comment by loretoparisi** [comment]
uhm  it actually has an intro with bass sounds, and then it raises up (keyboard, guitar, etc.).
By the way if I pass sample rate 22050 I get

```
fftData len=505
draw line x1=450 y1=20 x2=409 y2=2
draw line x1=450 y1=20 x2=396 y2=2
draw line x1=450 y1=20 x2=393 y2=2
draw line x1=476 y1=20 x2=409 y2=2
draw line x1=476 y1=20 x2=396 y2=2
draw line x1=476 y1=20 x2=393 y2=2
draw line x1=478 y1=2 x2=475 y2=20
draw line x1=478 y1=2 x2=449 y2=20
draw line x1=481 y1=2 x2=475 y2=20
draw line x1=481 y1=2 x2=449 y2=20
...
```
and the landmarks but If I pass the actual sample rate that is 48000 I get anything than `fftData len=512`, so it seems some error occurs...

**Comment by dest4** [comment]
My first suggestion was a mistake. Stay with `-ar 22050` or at least have the same value between ffmpeg and the landmark source code.

My view on your question is that you are only plotting the beginning of the track. So you get bass, and almost no fingerprints, which is normal.

**Comment by loretoparisi** [comment]
yep! that's true, I have changed the track and now I get something clearer

![out-fft](https://user-images.githubusercontent.com/163333/50355449-02db6a00-054f-11e9-8fde-23327b673658.png)
![out-thr](https://user-images.githubusercontent.com/163333/50355450-02db6a00-054f-11e9-8659-f560c28b670c.png)

so this means that the plot does not take in account the whole song, that's why for the first song with the intro I was getting that plot, is it possibile?

**Comment by dest4** [comment]
Plotting the whole track leads to very big pictures, so I only plot a fraction of it by default.
Please change your copy of the source code according to your needs.

**Comment by loretoparisi** [comment]
@dest4 perfect it makes sense thank you!!!
