### ISSUE TITLE
Interrupt fingerprinting process

### ISSUE THREAD

**Issue by ii64** [dest4/stream-audio-fingerprint#11]
![image](https://user-images.githubusercontent.com/26342994/50442162-3ee84380-0930-11e9-8718-06626f2d9f00.png)
Any chance to stop the fingerprinting process instead leave it untill it emit `'end' event`?
Figure1.1: Audio recognized as `A Music`
Figure1.2: End fingerprinting process because the Music already fingerprinted
Thank you, Anyway Merry Christmas! 😃

**Comment by dest4** [comment]
Hi,
just stop piping audio in the fingerprinter module?
Say if you have
```
decoder.stdout.pipe(fingerprinter);
```
write something like:
```
decoder.stdin.end()
```
You can also manually unpipe and end the fingerprinter Transform stream.

This seems to be a Node.js question, not an issue related to the fingerprinter.

**Comment by ii64** [comment]
> You can also manually unpipe and end the fingerprinter Transform stream.

Okay got that thing works, thank you
