### ISSUE TITLE
It is not an issue, help request

### ISSUE THREAD

**Issue by emrexhepi** [dest4/stream-audio-fingerprint#12]
Sorry to bother but any lead on how to match 2 fingerprints ?

Say I have generated some fingerprints and saved to a database, and now have a radio stream and want to match againts that database. Any lead on this ?

Thanks a lot for your work.

**Comment by dest4** [comment]
This is not a trivial topic, I should write a technical note about it some day.

What can help you today is the code I use for Adblock Radio to catch ads https://github.com/adblockradio/adblockradio/blob/master/predictor-db/hotlist.js#L150
(between lines 150 and 275)

**Comment by emrexhepi** [comment]
Thank you man also one more question, does this algorithm have tolerance ?
Like does it detect when audios speed is increased/decreased maybe change of pitch ?

Also this works just fine in windows you can add "type sample.mp3 | node codegen_demo.js" this command for windows users.

**Comment by dest4** [comment]
This algorithm does not work well when the playback speed and/or the pitch is changed.

You have more advanced algorithms that might suit your needs, such as Panako.
http://panako.be/releases/Panako-latest/readme.html

Thanks for the Windows command

**Comment by emrexhepi** [comment]
Thank you :)

**Comment by ACR4daFuture** [comment]
Also interested to do this.  I have been following this to learn how to do
matching db against audio stream
