### ISSUE TITLE
Consistent Hashes size among dataset

### ISSUE THREAD

**Issue by loretoparisi** [dest4/stream-audio-fingerprint#13]
I would like to keep all the `hcodes` array hashes of the same size for every audio sample. Now assumed that we consider the same file chunk size for each audio sample, would be that possibile?

**Comment by dest4** [comment]
Uh, if you add enough zeros in front of each hash, aren't all hashes of the same size?

**Comment by loretoparisi** [comment]
@dest4 okay so I should add padding, let me try then, it makes sense.

**Comment by loretoparisi** [comment]
@dest4 so I have padded my arrays to the max len

```javascript
            var max = 0;
            for (var i in hashes) {
                var row = hashes[i];
                if (max < row.length) max = row.length;
            }
            // padding
            for (var j in hashes) {
                var row = hashes[j];
                // zeros array
                var zeros = [];
                for (var i = 0; i < (max-row.length); i++) zeros[i] = 0;
                if(row.length<max) hashes[j]=zeros.concat(row);
            }
```

thank you.
