### ISSUE TITLE
Question: What was reasoning behind the hash function?

### ISSUE THREAD

**Issue by francomendoza** [dest4/stream-audio-fingerprint#16]
I'm trying to understand why this function was chosen?  Or could you break it down? Maybe I'm missing something obvious... Thanks!

```
f(freq(t1), freq(t2), dt) = freq(t1) + NFFT/2 * (freq(t2) + NFFT/2 * dt)
```

https://github.com/adblockradio/stream-audio-fingerprint/blob/2cd08736aaef489f2dc100b7a59878dddd4a90da/codegen_landmark.js#L259

**Comment by dest4** [comment]
Hi,
frequencies are numbers that lie in the range 0 and NFFT / 2 (excluded).
We want the final fingerprint to be a number that contains all information. Here is how, given the fingerprint F, we can get back to the original three parameters:
```
freq(t1) = F % NFFT/2
F = (F - freq(t1) / (NFFT/2)
freq(t2) = F % NFFT/2
F = (F - freq(t2) / (NFFT/2)
dt = F
```
(NB: % is the modulo operator)

It's a bit the poor man's implementation of protocol buffers https://github.com/protocolbuffers/protobuf
Is it clearer to you?

**Comment by francomendoza** [comment]
@dest4 yep that helped, i see its set up to use the modulo to derive each original parameter.  Thanks!
