### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event   && bash: nodejs: command not found

### ISSUE THREAD

**Issue by pohsiu** [dest4/stream-audio-fingerprint#2]
> Louisde-MBP:stream-audio-fingerprint louis$ sudo curl http://radiofg.impek.com/fg | nodejs codegen_demo.js
bash: nodejs: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17376    0 17376    0     0   6608      0 --:--:--  0:00:02 --:--:--  6609
curl: (23) Failed writing body (0 != 1448)

I figured maybe just my problem so I also tried this below:

> Louisde-MBP:stream-audio-fingerprint louis$ curl http://radiofg.impek.com/fg | node codegen_demo.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
100 23168    0 23168    0     0  11617      0 --:--:--  0:00:01 --:--:-- 11613
curl: (23) Failed writing body (0 != 8688)

Still failed

**Comment by dest4** [comment]
You need to have ffmpeg available.
What happens when you open a terminal and run `ffmpeg` ?
You may want to install it if not already the case: [https://ffmpeg.org/download.html](https://ffmpeg.org/download.html)

**Comment by pohsiu** [comment]
thx!! it works!
