### ISSUE TITLE
Get second from tcodes

### ISSUE THREAD

**Issue by ii64** [dest4/stream-audio-fingerprint#8]
![image](https://user-images.githubusercontent.com/26342994/50212855-ae998400-03ae-11e9-8b83-1705a49a5b9e.png)
Hi i want to convert tcodes to seconds, is there any way to convert the `tcodes` to the actual `seconds` on the music? (i have the original song fingerprint on the db, the hashes shown on the image is just a part of the original one)
Also, is the hash generator sensitive about distortion, noise and the other audio glitch? (i hope not)

**Comment by dest4** [comment]
Hello,
`tcodes` are in `DT` units.
As per https://github.com/adblockradio/stream-audio-fingerprint/blob/master/codegen_landmark.js#L48, you have `DT = 1 / (sample_rate / step)`. With default parameters, `sample_rate = 22050 Hz` and `step = 256`, so `DT ~ 11,61 ms`.

Moderate noise should not be a problem. Distortion might be (faster playback, different pitch…). Audio glitches may give you segments that get separately recognized (in case some audio frames are skipped), or will give you wrong fingerprints just before and after the glitch. Your detection algorithm should be resilient to handle that.

**Comment by ii64** [comment]
Is hash unique? i mean like if there's `112837` and `112838` are they similar?

**Comment by dest4** [comment]
Yes hash is unique. Close numbers are not (much) related.

**Comment by ii64** [comment]
Alright thank you, case closed
